services:
  redis:
    image: redis:alpine
    command: ["redis-server","--save","60","1","--loglevel","warning"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB:       judge0
      POSTGRES_USER:     judge0
      POSTGRES_PASSWORD: judge0
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  judge0:
    image: judge0/api:latest
    platform: linux/amd64
    depends_on:
      - redis
      - postgres
    ports:
      - "2358:3000"             # host 2358 → container 3000
    environment:
      DATABASE_URL: postgres://judge0:judge0@postgres:5432/judge0
      REDIS_URL:    redis://redis:6379
      RACK_ENV:     development
      # we no longer need PORT/WEB_CONCURRENCY here
    # ← override the default entrypoint/CMD and just run `rails server`
    command: ["sh", "-c", "bundle exec rails server -b 0.0.0.0 -p 3000"]

volumes:
  pgdata:
